package com.restrusher.ecomercecarlosv.data.local.dao

import app.cash.turbine.test
import com.restrusher.ecomercecarlosv.data.local.AppDatabase
import com.restrusher.ecomercecarlosv.data.local.entity.EntityType
import com.restrusher.ecomercecarlosv.data.local.entity.SyncOp
import com.restrusher.ecomercecarlosv.data.local.entity.SyncOperationEntity
import com.restrusher.ecomercecarlosv.support.createTestDatabase
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

@RunWith(RobolectricTestRunner::class)
class SyncOperationDaoTest {

    private lateinit var db: AppDatabase
    private lateinit var dao: SyncOperationDao

    @Before
    fun setUp() {
        db = createTestDatabase()
        dao = db.syncOperationDao()
    }

    @After
    fun tearDown() = db.close()

    private fun op(
        entityId: String = "pedido-1",
        operation: String = SyncOp.UPSERT,
        entityType: String = EntityType.PEDIDO,
        createdAt: Long = 1_000L,
    ) = SyncOperationEntity(
        entityType = entityType,
        entityId = entityId,
        operation = operation,
        createdAt = createdAt,
        entityLabel = "Bs. 100,00",
    )

    @Test
    fun `enqueue — assigns an autogenerated id`() = runTest {
        val id = dao.enqueue(op())

        assertEquals(1L, id)
        assertEquals(1, dao.pendingCount())
    }

    @Test
    fun `getPending — oldest first, so the queue replays in order`() = runTest {
        dao.enqueue(op(entityId = "b", createdAt = 9_000L))
        dao.enqueue(op(entityId = "a", createdAt = 1_000L))

        assertEquals(listOf("a", "b"), dao.getPending().map { it.entityId })
    }

    @Test
    fun `incrementRetry — bumps only the targeted row`() = runTest {
        val first = dao.enqueue(op(entityId = "a"))
        dao.enqueue(op(entityId = "b"))

        dao.incrementRetry(first)

        val byEntity = dao.getPending().associate { it.entityId to it.retryCount }
        assertEquals(1, byEntity["a"])
        assertEquals(0, byEntity["b"])
    }

    @Test
    fun `resetAllRetryCount — clears every failure marker at once`() = runTest {
        val first = dao.enqueue(op(entityId = "a"))
        val second = dao.enqueue(op(entityId = "b"))
        dao.incrementRetry(first)
        dao.incrementRetry(second)

        dao.resetAllRetryCount()

        assertEquals(listOf(0, 0), dao.getPending().map { it.retryCount })
    }

    @Test
    fun `deduplicateUpserts — collapses repeated upserts for the same entity`() = runTest {
        dao.enqueue(op(entityId = "pedido-1", createdAt = 1_000L))
        dao.enqueue(op(entityId = "pedido-1", createdAt = 2_000L))

        dao.deduplicateUpserts(EntityType.PEDIDO, "pedido-1")

        assertEquals(0, dao.pendingCount())
    }

    @Test
    fun `deduplicateUpserts — never removes a pending DELETE`() = runTest {
        dao.enqueue(op(entityId = "pedido-1", operation = SyncOp.UPSERT))
        dao.enqueue(op(entityId = "pedido-1", operation = SyncOp.DELETE))

        dao.deduplicateUpserts(EntityType.PEDIDO, "pedido-1")

        assertEquals(listOf(SyncOp.DELETE), dao.getPending().map { it.operation })
    }

    @Test
    fun `deduplicateUpserts — leaves other entities untouched`() = runTest {
        dao.enqueue(op(entityId = "pedido-1"))
        dao.enqueue(op(entityId = "pedido-2"))
        dao.enqueue(op(entityId = "pedido-1", entityType = EntityType.CLIENTE))

        dao.deduplicateUpserts(EntityType.PEDIDO, "pedido-1")

        assertEquals(2, dao.pendingCount())
    }

    @Test
    fun `observeLatestEnqueuedId — reports zero on an empty queue`() = runTest {
        dao.observeLatestEnqueuedId().test {
            assertEquals(0L, awaitItem())
        }
    }

    @Test
    fun `observeLatestEnqueuedId — advances on every enqueue, which is what triggers a flush`() =
        runTest {
            dao.observeLatestEnqueuedId().test {
                assertEquals(0L, awaitItem())

                dao.enqueue(op(entityId = "a"))

                assertEquals(1L, awaitItem())

                dao.enqueue(op(entityId = "b"))

                assertEquals(2L, awaitItem())
            }
        }

    @Test
    fun `delete — removes a flushed operation`() = runTest {
        val id = dao.enqueue(op())

        dao.delete(id)

        assertEquals(0, dao.pendingCount())
    }

    @Test
    fun `observeAll — re-emits as the queue drains`() = runTest {
        val id = dao.enqueue(op())

        dao.observeAll().test {
            assertEquals(1, awaitItem().size)

            dao.delete(id)

            assertEquals(emptyList<Any>(), awaitItem())
        }
    }
}
